### ISSUE TITLE
Duplicate functionality for FIB management

### ISSUE THREAD

**Issue by cawka** [NDN-Routing/NDNLP#3]
To create routes to a specific faces, it is possible to use ccndc command.  For example, instead of:

```
ndn@r1:~$ ndnldc -r -f 11 -n ccnx:/example
```

One can use:

```
ndn@r1:~$ ccndc add ccnx:/example face 11
```

**Comment by yoursunny** [comment]
This feature is added to ccndc after ndnldc is developed.

There should also be a prefix registration script:
1. accept <protocol,remote-addr,local-if> and one or more prefixes as arguments
2. find the FaceID of such as Face, create one if it doesn't exist
3. register the prefix(es) on this FaceID

It will be easier to use than requiring the user to look at the FaceID in stdout.
