### ISSUE TITLE
cannot create Ethernet face on Mac

### ISSUE THREAD

**Issue by cawka** [NDN-Routing/NDNLP#4]
Everything compiles and ndnld starts, but when I'm trying to create a "face" over ethernet using ndnldc, it times out with a strange error:

```
cawka-mac:~ ccnx$ ndnldc -c -p ether -h 3c:07:54:41:44:13 -i en0
ccn_get fails with code -1.
```

Is Mac officially not supported or there is a way to make it work?

**Comment by yoursunny** [comment]
ndnld currently uses AF_PACKET which is linux specific.
@tlbowman is porting the Ethernet face to use BPF, so it will work on Mac OS and hopefully FreeBSD.

**Comment by tlbowman** [comment]
Merged BPF into master
