### ISSUE TITLE
Need to handle stop/restart of ccnd

### ISSUE THREAD

**Issue by cawka** [NDN-Routing/NDNLP#5]
When ccnd stop or restarts, this should be handled in some way (either ndnlp should detect and reconnect, or just simply stop).  Right now, it is getting stuck in the loop with 100% utilization.

**Comment by yoursunny** [comment]
Steps to reproduce

```
ccndstart
sudo ndnld
ccndstop
top
```

Expected: ndnld should stop.
Actual: ndnld consumes 100% of one CPU core.

Suggested fix: ndnld should stop when the control face is dead.

**Comment by cawka** [comment]
May be stopping would be a good idea, provided that ndnld is somehow automatically restarted after ccnd is up again.   It is also relatively simple to solve 100% issue.

In `src/CcnClient.c` there is a call `ccn_run(ccnh, 0);` which in case stopped ccnd will immediately fail with code -1, and I suppose it will be immediately "rescheduled" again within ndnlp.   What you can do is to check if return value of ccn_run is negative, and if so, try to reconnect after some delay (e.g., using simple sleep). 

You can check our c++ ccnx wrapper implementation (specifically `CcnxWrapper::ccnLoop ()` method in https://github.com/named-data/ccnx-cpp/blob/master/ccnx/ccnx-wrapper.cpp#L188), which gives you an idea what should be done to successfully reconnect to ccnd when it is available.

**Comment by yoursunny** [comment]
ndnld should not attempt to reconnect. It should simply quit.
The environment start script should take care of starting ccnd, ndnld, ccnpingserver, etc; that script could also configure the services with ccndc, ndnldc, etc.

**Comment by tlbowman** [comment]
I looked into this, and found that ccn_run never gets called when we stop ccnd while ndnld is running.  ccn_run resides in CcnH_pollRun, which is called in a case of a switch statement in CcnCC_pollCb.  When ccnd is stopped, we continually enter the case 'PollMgrEvt_error', which sets self->error to true, but it looks like we will never stop entering this case.  Is this where I should put an 'exit()' call?

**Comment by yoursunny** [comment]
Calling `exit()` in `case PollMgrEvt_error:` branch is a good idea.
